pipeline:
  prep:
    image: library/debian:unstable
    commands:
      - apt-get update
      - apt-get -y install devscripts git-buildpackage
      - mk-build-deps --install -t'apt-get -y'
      - autoreconf -fis
      - ./configure
      - make
      - make check
